Workaround `rootfsPropagation: shared` brokenness.
Despite using `rootfsPropagation` after updating to Kubernetes v1.10 (not done
here yet) we are seeing:

    RunContainerError: failed to start container 4ea4bde9b43a9eb241a5d7d98abf87184938f85ce9139949a3a246b6fe6b8985":
      Error response from daemon:
        linux mounts: path /etc/kubernetes/pki/etcd is mounted on /etc/kubernetes but it is not a shared or slave mount

Workaround this by temporarily (re)doing it in the entrypoint.

Signed-off-by: Ian Campbell <ijc@docker.com>